version: "3"

services:
  fronted:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.fontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/app
    environment:
      API_TOKEN: ${API_TOKEN}
      API_URL: ${API_URL}
    networks:
      - strapi

  cms:
    image: dunadigital/strapi
    environment:
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_CLIENT: postgres
      DATABASE_PORT: 5432
      DATABASE_SSL: "false"
      NODE_ENV: ${NODE_ENV}
    ports:
      - 1337:1337
    volumes:
      - ./app:/srv/app
    depends_on:
      - db
    networks:
      - strapi

  db:
    container_name: postgres
    image: postgres:14.2
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - strapi

networks:
  strapi:
volumes:
  db:
